services:
  - type: web
    name: ravitobox-api
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: JWT_SECRET
        generateValue: true

  - type: static_site
    name: ravitobox-web
    rootDir: mobile
    buildCommand: npm install && npm run build:web
    staticPublishPath: dist
    pullRequestPreviewsEnabled: true
    envVars:
      - key: EXPO_PUBLIC_API_URL
        value: https://projetsportnature.onrender.com/api
      - key: EXPO_NO_BUNDLE_SPLITTING
        value: "1"
